on:
  pull_request:
    branches: [main]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: yarn bootstrap

      - name: Test code
        run: yarn test --coverage

      - name: Upload code coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Lint commit message
        uses: wagoid/commitlint-github-action@v4

      # - name: Lint code
      #   run: yarn lint

      - name: Typecheck code
        run: yarn typescript
