name: Prerelease

on:
  workflow_dispatch:
    inputs:
      version_bump_type:
        description: 'Would you like to manually control the version bump?'
        required: false
        default: ''
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  prerelease:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Install SSH Client
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Install lib dependencies
        run: yarn install

      - name: Set Git credentials
        run: |
          git config user.email "aryella.lacerda@gmail.com"
          git config user.name "Aryella"

      - name: Prepend node path
        run: npm config set scripts-prepend-node-path auto

      - name: Generate version number, commit, tag, and GitHub release
        run: yarn release ${{ inputs.version_bump_type }} --ci --preRelease=rc

      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
